// src/webui/src/components/chat-message/index.tsx
import { useEffect, useRef, useState } from 'react'
import { Box, Text, Flex } from '@chakra-ui/react'
import { ChevronDown, ChevronRight } from 'lucide-react'
import type { SessionMessage } from '@/api/gateway'
import ToolCallBlock from './ToolCallBlock'
import SubAgentBlock from './SubAgentBlock'

let mermaidCounter = 0

function escapeHtml(content: string): string {
  return content
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

function createFallbackHtml(content: string): string {
  return escapeHtml(content).replaceAll('\n', '<br />')
}

interface MarkdownRuntime {
  renderHtml: (content: string) => string
}

let markdownRuntimePromise: Promise<MarkdownRuntime> | null = null
let mermaidRuntimePromise: Promise<((container: HTMLElement) => Promise<void>)> | null = null

function getMarkdownRuntime(): Promise<MarkdownRuntime> {
  if (markdownRuntimePromise) {
    return markdownRuntimePromise
  }

  markdownRuntimePromise = Promise.all([
    import('marked'),
    import('highlight.js/lib/common'),
    import('dompurify'),
  ]).then(([markedModule, highlightModule, domPurifyModule]) => {
    const { marked } = markedModule
    const highlight = highlightModule.default
    const DOMPurify = domPurifyModule.default

    marked.use({
      async: false,
      renderer: {
        code({ text, lang }) {
          if (lang === 'mermaid') {
            return `<div class="mermaid-block" data-graph="${encodeURIComponent(text)}"></div>`
          }

          const validLang = lang && highlight.getLanguage(lang) ? lang : 'plaintext'
          const highlighted = highlight.highlight(text, { language: validLang }).value
          return `<pre><code class="hljs language-${validLang}">${highlighted}</code></pre>`
        },
      },
    })

    return {
      renderHtml(content: string) {
        return DOMPurify.sanitize(marked.parse(content) as string)
      },
    }
  }).catch((error) => {
    markdownRuntimePromise = null
    throw error
  })

  return markdownRuntimePromise
}

function getMermaidRuntime(): Promise<(container: HTMLElement) => Promise<void>> {
  if (mermaidRuntimePromise) {
    return mermaidRuntimePromise
  }

  mermaidRuntimePromise = Promise.all([
    import('dompurify'),
    import('mermaid/dist/mermaid.core.mjs'),
  ]).then(([domPurifyModule, mermaidModule]) => {
    const DOMPurify = domPurifyModule.default
    const mermaid = mermaidModule.default

    mermaid.initialize({ startOnLoad: false, theme: 'default', securityLevel: 'loose' })

    return async (container: HTMLElement) => {
      const blocks = container.querySelectorAll<HTMLElement>('.mermaid-block')

      for (const block of blocks) {
        const graph = decodeURIComponent(block.getAttribute('data-graph') ?? '')
        if (!graph) {
          continue
        }

        try {
          const id = `mermaid-${++mermaidCounter}`
          const { svg } = await mermaid.render(id, graph)
          block.innerHTML = DOMPurify.sanitize(svg, { FORCE_BODY: true })
        } catch {
          block.innerHTML = '<pre style="color:red">Mermaid 渲染失败</pre>'
        }
      }
    }
  }).catch((error) => {
    mermaidRuntimePromise = null
    throw error
  })

  return mermaidRuntimePromise
}

interface ChatMessageProps {
  message: SessionMessage
  isStreaming?: boolean
  /** 配对的结果消息（tool_result / sub_agent_result） */
  resultMessage?: SessionMessage | null
  /** 子代理进度步骤 */
  progressSteps?: string[]
}

function ThinkBlock({ content }: { content: string }) {
  const [open, setOpen] = useState(false)
  return (
    <Box
      borderWidth="1px"
      borderRadius="md"
      borderColor="purple.200"
      _dark={{ borderColor: 'purple.700' }}
      mb="2"
      overflow="hidden"
    >
      <Flex
        align="center"
        gap="1"
        px="3"
        py="1"
        bg="purple.50"
        _dark={{ bg: 'purple.900' }}
        cursor="pointer"
        onClick={() => setOpen(!open)}
        userSelect="none"
      >
        {open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
        <Text fontSize="xs" color="purple.600" _dark={{ color: 'purple.300' }}>
          思考过程
        </Text>
      </Flex>
      {open && (
        <Box
          px="3"
          py="2"
          fontSize="xs"
          color="gray.600"
          _dark={{ color: 'gray.400', bg: 'purple.950' }}
          whiteSpace="pre-wrap"
          fontFamily="mono"
          bg="purple.50"
        >
          {content}
        </Box>
      )}
    </Box>
  )
}

function MarkdownContent({ content }: { content: string }) {
  const ref = useRef<HTMLDivElement>(null)
  const [html, setHtml] = useState(() => createFallbackHtml(content))
  const [runtime, setRuntime] = useState<MarkdownRuntime | null>(null)

  useEffect(() => {
    let cancelled = false

    setHtml(createFallbackHtml(content))

    void getMarkdownRuntime()
      .then((nextRuntime) => {
        if (cancelled) {
          return
        }

        setRuntime(nextRuntime)
        setHtml(nextRuntime.renderHtml(content))
      })
      .catch(() => {
        if (!cancelled) {
          setRuntime(null)
          setHtml(createFallbackHtml(content))
        }
      })

    return () => {
      cancelled = true
    }
  }, [content])

  useEffect(() => {
    if (!ref.current || !runtime) {
      return
    }

    const hasMermaidBlocks = ref.current.querySelector('.mermaid-block')
    if (!hasMermaidBlocks) {
      return
    }

    let cancelled = false

    void getMermaidRuntime()
      .then(async (renderMermaidBlocks) => {
        if (cancelled || !ref.current) {
          return
        }

        await renderMermaidBlocks(ref.current)
      })
      .catch(() => {
        if (!cancelled && ref.current) {
          const blocks = ref.current.querySelectorAll<HTMLElement>('.mermaid-block')
          for (const block of blocks) {
            block.innerHTML = '<pre style="color:red">Mermaid 加载失败</pre>'
          }
        }
      })

    return () => {
      cancelled = true
    }
  }, [html, runtime])

  return (
    <Box
      ref={ref}
      className="md-content"
      fontSize="sm"
      lineHeight="1.7"
      dangerouslySetInnerHTML={{ __html: html }}
      css={{
        '& p': { marginBottom: '0.5em' },
        '& p:last-child': { marginBottom: 0 },
        '& pre': { borderRadius: '6px', overflow: 'auto', padding: '12px', background: '#1e1e1e', color: '#d4d4d4', fontSize: '0.85em', marginBottom: '0.5em' },
        '& code:not(pre > code)': { background: 'rgba(0,0,0,0.08)', borderRadius: '3px', padding: '1px 4px', fontSize: '0.85em', fontFamily: 'monospace' },
        '& ul, & ol': { paddingLeft: '1.5em', marginBottom: '0.5em' },
        '& blockquote': { borderLeft: '3px solid', borderColor: 'gray.300', paddingLeft: '0.75em', color: 'gray.500', marginBottom: '0.5em' },
        '& table': { borderCollapse: 'collapse', width: '100%', marginBottom: '0.5em' },
        '& th, & td': { border: '1px solid', borderColor: 'gray.200', padding: '4px 8px' },
        '& a': { color: 'blue.400', textDecoration: 'underline' },
        '& h1, & h2, & h3': { fontWeight: 'bold', marginBottom: '0.3em' },
      }}
    />
  )
}

const fadeInUp = {
  animation: 'fadeInUp 0.25s ease-out',
  '@keyframes fadeInUp': {
    from: { opacity: 0, transform: 'translateY(8px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
  },
}

export default function ChatMessage({ message, isStreaming, resultMessage, progressSteps }: ChatMessageProps) {
  const isUser = message.role === 'user'
  const contentRef = useRef<HTMLDivElement>(null)

  // tool_result / sub_agent_result 由配对的 start 消息渲染，不单独显示
  if (message.messageType === 'tool_result' || message.messageType === 'sub_agent_result') {
    return null
  }

  // 工具调用
  if (message.messageType === 'tool_call') {
    return (
      <Flex justify="flex-start" mb="3" px="2" css={fadeInUp}>
        <ToolCallBlock message={message} resultMessage={resultMessage} />
      </Flex>
    )
  }

  // 子代理
  if (message.messageType === 'sub_agent_start') {
    return (
      <Flex justify="flex-start" mb="3" px="2" css={fadeInUp}>
        <SubAgentBlock message={message} resultMessage={resultMessage} progressSteps={progressSteps} />
      </Flex>
    )
  }

  return (
    <Flex
      justify={isUser ? 'flex-end' : 'flex-start'}
      mb="3"
      px="2"
      css={fadeInUp}
    >
      <Box
        maxW="80%"
        bg={isUser ? 'blue.500' : 'white'}
        color={isUser ? 'white' : 'gray.800'}
        _dark={{
          bg: isUser ? 'blue.600' : 'gray.700',
          color: isUser ? 'white' : 'gray.100',
        }}
        borderRadius="lg"
        px="4"
        py="3"
        boxShadow="sm"
      >
        {/* Think block */}
        {message.thinkContent && (
          <ThinkBlock content={message.thinkContent} />
        )}

        {/* Main content */}
        <Box ref={contentRef}>
          {isUser ? (
            <Text fontSize="sm" whiteSpace="pre-wrap" wordBreak="break-word">
              {message.content}
            </Text>
          ) : (
            <MarkdownContent content={message.content} />
          )}
        </Box>

        {/* Streaming cursor */}
        {isStreaming && (
          <Box
            display="inline-block"
            w="2px"
            h="14px"
            bg="current"
            ml="1"
            animation="blink 1s step-end infinite"
            verticalAlign="text-bottom"
          />
        )}

        {/* Attachments */}
        {message.attachments && message.attachments.length > 0 && (
          <Flex mt="2" gap="2" flexWrap="wrap">
            {message.attachments.map((att, i) => (
              att.mimeType?.startsWith('image/') ? (
                <Box key={i} borderRadius="md" overflow="hidden" maxW="200px">
                  <img
                    src={`data:${att.mimeType};base64,${att.base64Data}`}
                    alt={att.fileName}
                    style={{ maxWidth: '100%', display: 'block' }}
                  />
                </Box>
              ) : (
                <Flex
                  key={i}
                  align="center"
                  gap="1"
                  px="2"
                  py="1"
                  borderRadius="md"
                  bg="blackAlpha.100"
                  fontSize="xs"
                >
                  📎 {att.fileName}
                </Flex>
              )
            ))}
          </Flex>
        )}
      </Box>
    </Flex>
  )
}

// src/webui/src/components/ChatMessage.vue
<template>
  <div class="chat-message" :class="msg.role">
    <!-- 头像 -->
    <div class="avatar">
      <el-icon v-if="msg.role === 'user'" :size="20"><User /></el-icon>
      <el-icon v-else :size="20"><Cpu /></el-icon>
    </div>

    <div class="bubble-wrapper">
      <!-- Think 块（可折叠） -->
      <div v-if="msg.thinkContent" class="think-block">
        <div class="think-header" @click="thinkOpen = !thinkOpen">
          <el-icon :size="14"><Loading v-if="isStreaming && !msg.thinkContent" /><Memo v-else /></el-icon>
          <span>思考过程</span>
          <el-icon :size="12" class="chevron" :class="{ open: thinkOpen }"><ArrowDown /></el-icon>
        </div>
        <div v-show="thinkOpen" class="think-content" v-html="renderMd(msg.thinkContent)" />
      </div>

      <!-- 用户消息：纯文字，显示附件 -->
      <template v-if="msg.role === 'user'">
        <div class="bubble user-bubble">
          <div class="message-text">{{ msg.content }}</div>
          <!-- 附件预览 -->
          <div v-if="msg.attachments && msg.attachments.length > 0" class="attachments">
            <template v-for="att in msg.attachments" :key="att.fileName">
              <div v-if="att.mimeType.startsWith('image/')" class="attachment-img">
                <img :src="`data:${att.mimeType};base64,${att.base64Data}`" :alt="att.fileName" />
              </div>
              <div v-else class="attachment-file">
                <el-icon><Document /></el-icon>
                <span>{{ att.fileName }}</span>
              </div>
            </template>
          </div>
        </div>
      </template>

      <!-- AI 消息：Markdown 渲染 -->
      <template v-else>
        <div class="bubble assistant-bubble">
          <div
            v-if="msg.content"
            class="markdown-body"
            v-html="renderedContent"
          />
          <span v-else class="typing-cursor">▍</span>
        </div>
      </template>

      <div class="timestamp">{{ formatTime(msg.timestamp) }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch, nextTick } from 'vue'
import { marked, Renderer } from 'marked'
import hljs from 'highlight.js'
import DOMPurify from 'dompurify'
import mermaid from 'mermaid'
import type { SessionMessage } from '@/stores/sessionStore'
import { User, Cpu, Memo, ArrowDown, Document, Loading } from '@element-plus/icons-vue'

const props = defineProps<{
  msg: SessionMessage
  isStreaming?: boolean
}>()

const thinkOpen = ref(false)
let mermaidCounter = 0

mermaid.initialize({
  startOnLoad: false,
  theme: 'neutral',
  securityLevel: 'loose'
})

// 配置 marked：代码高亮 + mermaid 特殊处理
const renderer = new Renderer()

renderer.code = ({ text, lang }: { text: string; lang?: string }) => {
  const language = lang ?? ''
  if (language === 'mermaid') {
    const id = `mermaid-${Date.now()}-${mermaidCounter++}`
    return `<div class="mermaid-block" data-mermaid="${encodeURIComponent(text)}" data-id="${id}"><div id="${id}">${text}</div></div>`
  }
  const validLang = hljs.getLanguage(language) ? language : 'plaintext'
  const highlighted = hljs.highlight(text, { language: validLang }).value
  return `<pre><code class="hljs language-${validLang}">${highlighted}</code></pre>`
}

marked.use({ renderer })

function renderMd(content: string): string {
  const raw = marked.parse(content) as string
  return DOMPurify.sanitize(raw, { ADD_ATTR: ['data-mermaid', 'data-id'] })
}

const renderedContent = computed(() => renderMd(props.msg.content))

// 渲染 mermaid 图表
async function renderMermaidBlocks(el: Element) {
  const blocks = el.querySelectorAll<HTMLElement>('.mermaid-block')
  for (const block of blocks) {
    const encoded = block.getAttribute('data-mermaid')
    const id = block.getAttribute('data-id')
    if (!encoded || !id) continue
    const code = decodeURIComponent(encoded)
    const target = block.querySelector(`#${id}`)
    if (!target) continue
    try {
      const { svg } = await mermaid.render(id + '-svg', code)
      target.innerHTML = svg
    } catch {
      target.textContent = code
    }
  }
}

// 每次内容变化后渲染 mermaid
watch(renderedContent, async () => {
  await nextTick()
  const el = document.querySelector('.chat-messages')
  if (el) renderMermaidBlocks(el)
})

onMounted(async () => {
  await nextTick()
  const el = document.querySelector('.chat-messages')
  if (el) renderMermaidBlocks(el)
})

function formatTime(ts: string): string {
  return new Date(ts).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })
}
</script>

<style scoped>
.chat-message {
  display: flex;
  gap: 10px;
  padding: 8px 0;
}

.chat-message.user {
  flex-direction: row-reverse;
}

.avatar {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  background: var(--el-fill-color);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  margin-top: 2px;
}

.chat-message.user .avatar {
  background: var(--el-color-primary-light-7);
}

.bubble-wrapper {
  max-width: 75%;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.chat-message.user .bubble-wrapper {
  align-items: flex-end;
}

.bubble {
  padding: 10px 14px;
  border-radius: 12px;
  line-height: 1.6;
  word-break: break-word;
}

.user-bubble {
  background: var(--el-color-primary);
  color: #fff;
  border-bottom-right-radius: 4px;
}

.user-bubble .message-text {
  white-space: pre-wrap;
}

.assistant-bubble {
  background: var(--el-fill-color-light);
  border-bottom-left-radius: 4px;
  min-width: 40px;
}

.typing-cursor {
  display: inline-block;
  animation: blink 1s step-end infinite;
  color: var(--el-color-primary);
  font-size: 18px;
  line-height: 1;
}

@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}

.timestamp {
  font-size: 11px;
  color: var(--el-text-color-placeholder);
  padding: 0 2px;
}

/* Think 块 */
.think-block {
  background: var(--el-fill-color-lighter);
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  overflow: hidden;
  font-size: 13px;
}

.think-header {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 12px;
  cursor: pointer;
  user-select: none;
  color: var(--el-text-color-secondary);
  font-weight: 500;
}

.think-header:hover {
  background: var(--el-fill-color);
}

.chevron {
  margin-left: auto;
  transition: transform 0.2s;
}

.chevron.open {
  transform: rotate(180deg);
}

.think-content {
  padding: 0 12px 10px;
  color: var(--el-text-color-secondary);
  border-top: 1px solid var(--el-border-color-lighter);
  font-size: 13px;
}

/* 附件 */
.attachments {
  margin-top: 8px;
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.attachment-img img {
  max-width: 200px;
  max-height: 200px;
  border-radius: 6px;
  object-fit: cover;
}

.attachment-file {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  background: rgba(255,255,255,0.2);
  border-radius: 4px;
  font-size: 13px;
}

/* Markdown 样式 */
.markdown-body :deep(p) {
  margin: 4px 0 8px;
}

.markdown-body :deep(h1),
.markdown-body :deep(h2),
.markdown-body :deep(h3) {
  margin: 12px 0 6px;
  font-weight: 600;
}

.markdown-body :deep(code:not(pre > code)) {
  background: var(--el-fill-color);
  padding: 1px 5px;
  border-radius: 4px;
  font-family: 'Courier New', monospace;
  font-size: 0.9em;
}

.markdown-body :deep(pre) {
  background: #1e1e1e;
  border-radius: 8px;
  padding: 12px 16px;
  overflow-x: auto;
  margin: 8px 0;
}

.markdown-body :deep(pre code) {
  background: transparent;
  padding: 0;
  color: #d4d4d4;
  font-size: 13px;
  font-family: 'Courier New', Consolas, monospace;
}

.markdown-body :deep(blockquote) {
  border-left: 3px solid var(--el-color-primary);
  margin: 8px 0;
  padding: 4px 12px;
  color: var(--el-text-color-secondary);
  background: var(--el-fill-color-lighter);
  border-radius: 0 4px 4px 0;
}

.markdown-body :deep(ul),
.markdown-body :deep(ol) {
  padding-left: 20px;
  margin: 4px 0 8px;
}

.markdown-body :deep(table) {
  border-collapse: collapse;
  width: 100%;
  margin: 8px 0;
  font-size: 13px;
}

.markdown-body :deep(th),
.markdown-body :deep(td) {
  border: 1px solid var(--el-border-color);
  padding: 6px 10px;
  text-align: left;
}

.markdown-body :deep(th) {
  background: var(--el-fill-color);
  font-weight: 600;
}

.markdown-body :deep(.mermaid-block) {
  margin: 8px 0;
  overflow-x: auto;
}

.markdown-body :deep(.mermaid-block svg) {
  max-width: 100%;
}
</style>
